package com.example.dealspy.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF465D91)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD9E2FF)
val onPrimaryContainerLight = Color(0xFF2D4678)
val secondaryLight = Color(0xFF575E71)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDBE2F9)
val onSecondaryContainerLight = Color(0xFF3F4759)
val tertiaryLight = Color(0xFF545A92)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFDFE0FF)
val onTertiaryContainerLight = Color(0xFF3C4279)
val errorLight = Color(0xFF904A49)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD8)
val onErrorContainerLight = Color(0xFF733332)
val backgroundLight = Color(0xFFFAF9FF)
val onBackgroundLight = Color(0xFF1A1B20)
val surfaceLight = Color(0xFFFAF9FF)
val onSurfaceLight = Color(0xFF1A1B20)
val surfaceVariantLight = Color(0xFFE1E2EC)
val onSurfaceVariantLight = Color(0xFF44464F)
val outlineLight = Color(0xFF757780)
val outlineVariantLight = Color(0xFFC5C6D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3036)
val inverseOnSurfaceLight = Color(0xFFF1F0F7)
val inversePrimaryLight = Color(0xFFAFC6FF)
val surfaceDimLight = Color(0xFFDAD9E0)
val surfaceBrightLight = Color(0xFFFAF9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F3FA)
val surfaceContainerLight = Color(0xFFEEEDF4)
val surfaceContainerHighLight = Color(0xFFE8E7EF)
val surfaceContainerHighestLight = Color(0xFFE2E2E9)

val primaryLightMediumContrast = Color(0xFF1A3566)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF556CA1)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF2F3648)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF666D80)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF2B3167)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF6269A2)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF5E2323)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFA15856)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFAF9FF)
val onBackgroundLightMediumContrast = Color(0xFF1A1B20)
val surfaceLightMediumContrast = Color(0xFFFAF9FF)
val onSurfaceLightMediumContrast = Color(0xFF0F1116)
val surfaceVariantLightMediumContrast = Color(0xFFE1E2EC)
val onSurfaceVariantLightMediumContrast = Color(0xFF34363E)
val outlineLightMediumContrast = Color(0xFF50525A)
val outlineVariantLightMediumContrast = Color(0xFF6B6D75)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2F3036)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF1F0F7)
val inversePrimaryLightMediumContrast = Color(0xFFAFC6FF)
val surfaceDimLightMediumContrast = Color(0xFFC6C6CD)
val surfaceBrightLightMediumContrast = Color(0xFFFAF9FF)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF3F3FA)
val surfaceContainerLightMediumContrast = Color(0xFFE8E7EF)
val surfaceContainerHighLightMediumContrast = Color(0xFFDCDCE3)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD1D1D8)

val primaryLightHighContrast = Color(0xFF0D2A5B)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF30487B)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF252C3D)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF42495B)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF20275C)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF3E457B)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF51191A)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF763535)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFAF9FF)
val onBackgroundLightHighContrast = Color(0xFF1A1B20)
val surfaceLightHighContrast = Color(0xFFFAF9FF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE1E2EC)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF292C33)
val outlineVariantLightHighContrast = Color(0xFF474951)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2F3036)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFAFC6FF)
val surfaceDimLightHighContrast = Color(0xFFB8B8BF)
val surfaceBrightLightHighContrast = Color(0xFFFAF9FF)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF1F0F7)
val surfaceContainerLightHighContrast = Color(0xFFE2E2E9)
val surfaceContainerHighLightHighContrast = Color(0xFFD4D4DB)
val surfaceContainerHighestLightHighContrast = Color(0xFFC6C6CD)

val primaryDark = Color(0xFFAFC6FF)
val onPrimaryDark = Color(0xFF132F60)
val primaryContainerDark = Color(0xFF2D4678)
val onPrimaryContainerDark = Color(0xFFD9E2FF)
val secondaryDark = Color(0xFFBFC6DC)
val onSecondaryDark = Color(0xFF293042)
val secondaryContainerDark = Color(0xFF3F4759)
val onSecondaryContainerDark = Color(0xFFDBE2F9)
val tertiaryDark = Color(0xFFBDC2FF)
val onTertiaryDark = Color(0xFF252B61)
val tertiaryContainerDark = Color(0xFF3C4279)
val onTertiaryContainerDark = Color(0xFFDFE0FF)
val errorDark = Color(0xFFFFB3B0)
val onErrorDark = Color(0xFF571D1E)
val errorContainerDark = Color(0xFF733332)
val onErrorContainerDark = Color(0xFFFFDAD8)
val backgroundDark = Color(0xFF121318)
val onBackgroundDark = Color(0xFFE2E2E9)
val surfaceDark = Color(0xFF121318)
val onSurfaceDark = Color(0xFFE2E2E9)
val surfaceVariantDark = Color(0xFF44464F)
val onSurfaceVariantDark = Color(0xFFC5C6D0)
val outlineDark = Color(0xFF8F9099)
val outlineVariantDark = Color(0xFF44464F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E2E9)
val inverseOnSurfaceDark = Color(0xFF2F3036)
val inversePrimaryDark = Color(0xFF465D91)
val surfaceDimDark = Color(0xFF121318)
val surfaceBrightDark = Color(0xFF38393E)
val surfaceContainerLowestDark = Color(0xFF0C0E13)
val surfaceContainerLowDark = Color(0xFF1A1B20)
val surfaceContainerDark = Color(0xFF1E1F25)
val surfaceContainerHighDark = Color(0xFF282A2F)
val surfaceContainerHighestDark = Color(0xFF33353A)

val primaryDarkMediumContrast = Color(0xFFD0DCFF)
val onPrimaryDarkMediumContrast = Color(0xFF042355)
val primaryContainerDarkMediumContrast = Color(0xFF7890C7)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFD5DCF3)
val onSecondaryDarkMediumContrast = Color(0xFF1E2536)
val secondaryContainerDarkMediumContrast = Color(0xFF8990A5)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFD8DAFF)
val onTertiaryDarkMediumContrast = Color(0xFF1A2055)
val tertiaryContainerDarkMediumContrast = Color(0xFF868CC8)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CF)
val onErrorDarkMediumContrast = Color(0xFF481314)
val errorContainerDarkMediumContrast = Color(0xFFCB7A78)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF121318)
val onBackgroundDarkMediumContrast = Color(0xFFE2E2E9)
val surfaceDarkMediumContrast = Color(0xFF121318)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF44464F)
val onSurfaceVariantDarkMediumContrast = Color(0xFFDBDCE6)
val outlineDarkMediumContrast = Color(0xFFB0B1BB)
val outlineVariantDarkMediumContrast = Color(0xFF8E9099)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE2E2E9)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF282A2F)
val inversePrimaryDarkMediumContrast = Color(0xFF2E4779)
val surfaceDimDarkMediumContrast = Color(0xFF121318)
val surfaceBrightDarkMediumContrast = Color(0xFF43444A)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF06070C)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1C1D23)
val surfaceContainerDarkMediumContrast = Color(0xFF26282D)
val surfaceContainerHighDarkMediumContrast = Color(0xFF313238)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3C3D43)

val primaryDarkHighContrast = Color(0xFFECEFFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFAAC2FD)
val onPrimaryContainerDarkHighContrast = Color(0xFF000A23)
val secondaryDarkHighContrast = Color(0xFFECEFFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFBBC2D8)
val onSecondaryContainerDarkHighContrast = Color(0xFF040B1B)
val tertiaryDarkHighContrast = Color(0xFFF0EEFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFB8BEFD)
val onTertiaryContainerDarkHighContrast = Color(0xFF000337)
val errorDarkHighContrast = Color(0xFFFFECEA)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFADAA)
val onErrorContainerDarkHighContrast = Color(0xFF220002)
val backgroundDarkHighContrast = Color(0xFF121318)
val onBackgroundDarkHighContrast = Color(0xFFE2E2E9)
val surfaceDarkHighContrast = Color(0xFF121318)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF44464F)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFEFEFF9)
val outlineVariantDarkHighContrast = Color(0xFFC1C2CC)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE2E2E9)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF2E4779)
val surfaceDimDarkHighContrast = Color(0xFF121318)
val surfaceBrightDarkHighContrast = Color(0xFF4F5056)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1E1F25)
val surfaceContainerDarkHighContrast = Color(0xFF2F3036)
val surfaceContainerHighDarkHighContrast = Color(0xFF3A3B41)
val surfaceContainerHighestDarkHighContrast = Color(0xFF45464C)


val opt1_Primary_Background = Color(0xFF1A2B3C)
val opt1_Card_Background = Color(0xFF2C3E50)
val opt1_Text_Primary = Color(0xFFECF0F1)
val opt1_Text_Secondary_Discount = Color(0xFFBDC3C7)
val opt1_Price_Highlight = Color(0xFF1ABC9C)
val opt1_BuyNow_Button = Color(0xFF2ECC71)
val opt1_Timer_Background = Color(0xFFE74C3C)
val opt1_Timer_Text = Color(0xFFECF0F1)



val opt2_Primary_Background = Color(0xFF2C2C2C)
val opt2_Card_Background = Color(0xFF3D3D3D)
val opt2_Text_Primary = Color(0xFFF5F5F5)
val opt2_Text_Secondary_Discount = Color(0xFFCCCCCC)
val opt2_Price_Highlight = Color(0xFFFFB74D)
val opt2_BuyNow_Button = Color(0xFFFFA000)
val opt2_Timer_Background = Color(0xFFD32F2F)
val opt2_Timer_Text = Color(0xFFF5F5F5)



val opt3_Primary_Background = Color(0xFF0F3443)
val opt3_Card_Background = Color(0xFF1A4354)
val opt3_Text_Primary = Color(0xFFE0E0E0)
val opt3_Text_Secondary_Discount = Color(0xFFB0BEC5)
val opt3_Price_Highlight = Color(0xFFFFD54F)
val opt3_BuyNow_Button = Color(0xFF00BFA5)
val opt3_Timer_Background = Color(0xFFFF7043)
val opt3_Timer_Text = Color(0xFFE0E0E0)


val opt4_Primary_Background = Color(0xFF121212)
val opt4_Card_Background = Color(0xFF1E1E1E)
val opt4_Text_Primary = Color(0xFFF0F0F0)
val opt4_Text_Secondary_Discount = Color(0xFFBDBDBD)
val opt4_Price_Highlight = Color(0xFFBB86FC)
val opt4_BuyNow_Button = Color(0xFF03DAC6)
val opt4_Timer_Background = Color(0xFFCF6679)
val opt4_Timer_Text = Color(0xFFF0F0F0)



val opt5_Primary_Background = Color(0xFF0A2B2F)
val opt5_Card_Background = Color(0xFF1B3D40)
val opt5_Text_Primary = Color(0xFFE8F6F6)
val opt5_Text_Secondary_Discount = Color(0xFFA3C7C7)
val opt5_Price_Highlight = Color(0xFF7BC96A)
val opt5_BuyNow_Button = Color(0xFF4CAF50)
val opt5_Timer_Background = Color(0xFFD32F2F)
val opt5_Timer_Text = Color(0xFFE8F6F6)


val opt6_Primary_Background = Color(0xFF0F0F0F)
val opt6_Card_Background = Color(0xFF252525)
val opt6_Text_Primary = Color(0xFFFFFFFF)
val opt6_Text_Secondary_Discount = Color(0xFFCFCFCF)
val opt6_Price_Highlight = Color(0xFFFCA311)
val opt6_BuyNow_Button = Color(0xFFE85D04)
val opt6_Timer_Background = Color(0xFFCC2936)
val opt6_Timer_Text = Color(0xFFFFFFFF)










